[build]
  base = "client"
  publish = "build"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://product-traceability-api.onrender.com"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"
  NODE_ENV = "production"
  PUBLIC_URL = "/"
  # Ensure consistent builds
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Force correct MIME types for all JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Force correct MIME types for all CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Generic static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Main HTML file - no cache to prevent outdated builds
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Service Worker - no cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Asset manifest - no cache to ensure latest file references
[[headers]]
  for = "/asset-manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# CRITICAL: Direct static asset serving (highest priority)
[[redirects]]
  from = "/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/media/*"
  to = "/static/media/:splat"
  status = 200
  force = true

# Handle nested static asset paths
[[redirects]]
  from = "/*/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/static/media/*"
  to = "/static/media/:splat"
  status = 200
  force = true

# Handle double-nested paths
[[redirects]]
  from = "/*/*/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/*/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

# Root assets
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/asset-manifest.json"
  to = "/asset-manifest.json"
  status = 200
  force = true

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://product-traceability-api.onrender.com/api/:splat"
  status = 200

# SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
