[build]
  base = "client"
  publish = "build"
  command = "rm -rf node_modules build && npm install --legacy-peer-deps && CI=false npm run build"

[build.environment]
  REACT_APP_API_URL = "https://product-traceability-api.onrender.com"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

# Static asset headers for caching and security
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript MIME type headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# CSS MIME type headers
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Direct static asset redirects
[[redirects]]
  from = "/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/media/*"
  to = "/static/media/:splat"
  status = 200
  force = true

# Handle nested static asset paths (critical for deep routing)
[[redirects]]
  from = "/*/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/static/media/*"
  to = "/static/media/:splat"
  status = 200
  force = true

# Handle double-nested paths
[[redirects]]
  from = "/*/*/static/js/*"
  to = "/static/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/*/static/css/*"
  to = "/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*/*/static/media/*"
  to = "/static/media/:splat"
  status = 200
  force = true

# Root assets
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/asset-manifest.json"
  to = "/asset-manifest.json"
  status = 200
  force = true

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://product-traceability-api.onrender.com/api/:splat"
  status = 200

# SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
