[build]
  base = "client"
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

# Static assets should be served as-is (exclude from SPA routing)
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Manifest and other assets
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# SPA routing - redirect all non-static routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Additional security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.environment]
  REACT_APP_API_URL = "https://product-traceability-api.onrender.com"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
